### ISSUE TITLE
12 - Add Server page initial design

### ISSUE THREAD

**Issue by kelseydonavin** [kelseydonavin/MC_UI#14]
Pre-Requirements:
- Issue 10 is complete, temporary routing via /Server is usable

Requirements:
- Server page shall have "Server" title above table
- Sever page shall have table that has facts about the server 
- Table shall look similar to the below image

<img width="857" alt="Screen Shot 2019-10-17 at 7 29 01 PM" src="https://user-images.githubusercontent.com/27250560/67061187-61905680-f114-11e9-8cc1-83daf9fb413a.png">

**Comment by kelseydonavin** [comment]
Please adjust code to accommodate new menu

**Comment by kelseydonavin** [comment]
Please mimic the style of the server page which will be raftered in issue 23, refer to the striped table in this link for design https://getbootstrap.com/docs/4.3/content/tables/

**Comment by kkjw94** [comment]
server page done
