### ISSUE TITLE
34 - Get GraphQL set up

### ISSUE THREAD

**Issue by kelseydonavin** [kelseydonavin/MC_UI#61]
Pre-Requirements:
- Database is set up (currently assigned to Trenton)

Requirements:
- Get GraphQL set up for our database
- Should be setup to accept queries from the UI
-  Should be setup to run/ pass the queries through the database

SPIKE (research and answer below questions):
- Can GraphQL replace our current API?

**Comment by kelseydonavin** [comment]
New Requirement:
- Must set up a new git repo for this project, repo must have all team members as contributors

**Comment by ajaeminkim93** [comment]
[Cpts41Project.zip](https://github.com/kelseydonavin/MC_UI/files/3924822/Cpts41Project.zip)

Started practicing using graphql. This is a very simple example.
Inside a node.js command prompt:
     npm init -y            // initialize node.js application w/ package.json file

Now open the zip file and open in vs code.
Inside VScode:
     open terminal then...
     npm install express express-graphql
     npm install graphql
     npm install nodemon -D       // this will make it so you don't have to refresh server

Then open local host,     
     http://localhost:5000/graphql

**Comment by ajaeminkim93** [comment]
Example Query:
query {
   authors {
    name
    books {
      name
    }    
  }
}

**Comment by kelseydonavin** [comment]
Assigned in Sprint 5 (Fall Semester), moved to Sprint 6 (Spring Semester)

**Comment by lshearer20** [comment]
Over in our API github we've now switched from C# to node.js since node.js seems to be more common for graphql. Also set up a hard coded, very simple graphql in the node.js for the moment. 1f4feda51c2cdc64100de7d213b5c8510d4155df

**Comment by lshearer20** [comment]
I believe my commit in the above comment wasnt the full new node.js code so here it is https://github.com/kelseydonavin/AIMS_API/commit/e3dbeebf91c978412c02809e97f4241b06b71e9c

**Comment by lshearer20** [comment]
Graphql is set up and data flow is working with WSU con data + fake data schema for UI testing and implementation. API commit:https://github.com/kelseydonavin/AIMS_API/commit/738131f00923e6aef2241662f3ed0aa64391a1bd
UI commit: https://github.com/kelseydonavin/MC_UI/commit/daa50be9b508d8679176d6e64f2d0e3a3aa868c3

**Comment by lshearer20** [comment]
I created the sample/fake Data from WSU con. Uploaded it into firebase (which I had to change the schema slightly but not an issue for now), updated the API for the new WSUcon.JSON, changed the UI graphql Queries to query the data from the database with the new schemas the pages of, Server, Metrics, and Players. The page/component called /example-users has print outs of the data flow and a way to access the data being brought into the UI.
.
If you run the API with "npm start" you should be able to access the playground page to check that it works "http://localhost:4000/graphql/graphiql" with the left side being something like this query{
  players{
    PlayerName
    Time
    LoggedIn
    PlayerKilled
    Advancement
    BlockType
    BlocksMined
    MobsKilled
    PlayersKilled
    Trades
    TripsToNether
    AnimalsBred
  }
}
and it should produce the right side data from the database
.
If that works then the if you run the API, and go to "http://localhost:4200/example-users" you should see the print out of the same data from that playground in this page of the UI.
